#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Run this code to build tensorflow model and corresponding weight values for VNect
Require: 'params.pkl' which is generated by caffe2pkl.py
"""
import os
import tensorflow as tf


def load_tf_weights(pfile, spath, model):
    # configurations
    PARAMSFILE = pfile
    SAVERPATH = spath

    if not tf.gfile.Exists(SAVERPATH):
        tf.gfile.MakeDirs(SAVERPATH)

    with tf.Session() as sess:
        saver = tf.train.Saver()
        model.load_weights(sess, PARAMSFILE)
        saver.save(sess, os.path.join(SAVERPATH, 'vnect_tf'))
