root_dir = 'E:\Datasets\mpi_inf_3dhp';
cams = [0, 1, 2, 4, 5, 6, 7, 8] + 1;

if exist([root_dir, '\annot_h5'],'dir')~=0
    rmdir([root_dir, '\annot_h5'], 's');
end
mkdir([root_dir, '\annot_h5']);

for i=1:8  % S1-S8
    for j=1:2  % Seq1-Seq2
        load(sprintf('%s\\S%d\\Seq%d\\annot.mat', root_dir, i, j))
        for k=cams
            % create annot2/video_X
            h5create(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/annot2/video_%d', j, k-1),...
                [size(annot2{k,1}, 2), size(annot2{k,1}, 1)],...
                'Datatype', 'uint16');
            % create annot3/video_X
            h5create(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/annot3/video_%d', j, k-1),...
                [size(annot3{k,1}, 2), size(annot3{k,1}, 1)],...
                'Datatype', 'uint16');
            % create univ_annot3/video_X
            h5create(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/univ_annot3/video_%d', j, k-1),...
                [size(univ_annot3{k,1}, 2), size(univ_annot3{k,1}, 1)],...
                'Datatype', 'uint16');
            % write annot2/video_X
            h5write(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/annot2/video_%d', j, k-1),...
                annot2{k,1}'/2048*368);
            % write annot3/video_X
            h5write(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/annot3/video_%d', j, k-1),...
                annot3{k,1}'/2048*368);
            % write univ_annot3/video_X
            h5write(sprintf('%s\\annot_h5\\S%d.h5', root_dir, i),...
                sprintf('/Seq%d/univ_annot3/video_%d', j, k-1),...
                univ_annot3{k,1}'/2048*368);
        end
    end
end
disp('Done.')